### ISSUE TITLE
How would one go about utilizing this with a Edgerouter 4

### ISSUE THREAD

**Issue by nikolaishields** [Archerious/bgw210-root#5]
Additionally, could you lend any insight into utilizing a block of static ips using eap_proxy?

**Comment by ktreese** [comment]
I used a guide from [devicelocksmith](https://www.devicelocksmith.com/2019/01/configuring-8021x-authentication-using.html) for setting things up on an ER4.  Does this help?  You may need to make some adjustments depending how you have things setup (I had to)

**Comment by ktreese** [comment]
btw -- read through the comments on that thread as the link to downloading the wpa supplicant package as originally authored is a dead link.

**Comment by nikolaishields** [comment]
@ktreese thanks!
Over the last 4 days of irregular work, I was able to have this work.
do you have any experience utilizing a block of static ip's provided by att and wpa_supplicant on the ER4?

**Comment by ktreese** [comment]
@nikolaishields, I do not.  Glad you were able to get things going otherwise!

**Comment by ktreese** [comment]
@Archerious I think this issue can be closed as resolved.

**Comment by Archerious** [comment]
Glad you got it working, most of what I found from trial and error is posted on this thread: https://github.com/jaysoffian/eap_proxy/issues/18

Static IPv4 blocks are simple to setup on pfSense and Mikrotik but require more work on EdgeOS.
